name: twitter_oauth
description: Twitter Sign-in Library.
version: 0.0.1
author: Toi Yoshimaru <0maru.dev@gmail.com>
homepage: https://github.com/0maru/twitter_oauth

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  crypto: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
